import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")

#creating database and table
mycursor=mydb.cursor()
mycursor.execute("create database Project")
mycursor.execute("use Project")
j=True
while j==True:
    user=input("Enter your name:")
    print()
    print("Hello",user,"! Welcome to your telephone diary. ")
    print()
    mycursor.execute("Create table contact(Name varchar(50) , Phone_number char(10) PRIMARY KEY, group_name varchar(40),Address varchar(100),\
City varchar(50),Email varchar(50))")
    mydb.commit()
    while True:
        print("TO VIEW YOUR CONTACTS ENTER 1","TO ADD A CONTACT ENTER 2","TO SEARCH AND UPDATE A CONTACT ENTER 3","TO DELETE A CONTACT ENTER 4",\
              "TO CLOSE TELEPHONE DIARY ENTER 5",sep="\n")
        print()
        c=int(input("Enter your choice:"))
        if c == 1:
            mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
            mycursor=mydb.cursor()
            mycursor.execute("use project")
            print()
            mycursor.execute("select * from contact")
            r=mycursor.fetchall()
            for R in r:
                print(R)
            mydb.commit()
            print()
        elif c== 2:
            x=True
            while x==True:
                nm=input("Contact person's name:")
                p=input("Person's mobile number:")
                g=input("what group would you classify the person's contact(work, school,family, community,etc..):")
                a=input("Enter address of person:")
                city=input("Enter in which city does the person lives:")
                e=input("Enter email of the person:")
                mycursor.execute("insert into contact values('"+nm+"','"+p+"','"+g+"','"+a+"','"+city+"','"+e+"')")
                mydb.commit() 
                print("Contact added succesfully")
                print()
                f=input("would you like to continue to add more contact(yes/no)?")
                if f=='yes':
                    x=True
                elif f=='no':
                    x=False
                print()
        elif c==3:
            print("1:search by name","2:search by phone number","3:search by group","4:search by city","5:search by email",sep="\n")
            i=input("Search by?")
            if i=='1':
                name=input("Enter name of person you want contact:")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("select*from contact where Name = '"+name+"'")
                m=mycursor.fetchall()
                for M in m:
                    print(M)
                mydb.commit()
                print()
                var=input("Do you want to update this contact? Y/N")
                if var=='Y':
                    print("To update Name enter: a")
                    print("To update Phone number enter: b")
                    print("To update Group enter: c")
                    print("To update Address enter: d")
                    print("To update City enter: e")
                    print("To update Email enter: f")
                    v1=input("What do you want to update?")
                    if v1=='a':
                        e1=input("Enter new name: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Name = '"+e1+"' where Name = '"+name+"'")
                        print("Name updated")
                        mydb.commit()
                    if v1=='b':
                        e2=input("Enter new Phone Number: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Phone_number = '"+e2+"' where Name = '"+name+"'")
                        print("Phone number updated")
                        mydb.commit()
                    if v1=='c':
                        e3=input("Enter new group: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set group_name = '"+e3+"' where Name = '"+name+"'")
                        print("Group updated")
                        mydb.commit()
                    if v1=='d':
                        e4=input("Enter new address: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Address = '"+e4+"' where Name = '"+name+"'")
                        print("Address updated")
                        mydb.commit()
                    if v1=='e':
                        e5=input("Enter new city: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set City = '"+e5+"' where Name = '"+name+"'")
                        print("City updated")
                        mydb.commit() 
                    if v1=='f':
                        e6=input("Enter new Email: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Email = '"+e6+"' where Name = '"+name+"'")
                        print("Email updated")
                        mydb.commit()
                        print()
            elif i=='2':
                phone=input("Enter phone number:")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("select*from contact where Phone_number = '"+phone+"'")
                z=mycursor.fetchall()
                for Z in z:
                    print(Z)
                mydb.commit()
                print()
                var=input("Do you want to update this contact? Y/N")
                if var=='Y':
                    print("To update Name enter: a")
                    print("To update Phone number enter: b")
                    print("To update Group enter: c")
                    print("To update Address enter: d")
                    print("To update City enter: e")
                    print("To update Email enter: f")
                    v1=input("What do you want to update?")
                    if v1=='a':
                        e1=input("Enter new name: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Name = '"+e1+"' where Phone_number = '"+phone+"'")
                        print("Name updated")
                        mydb.commit()
                    if v1=='b':
                        e2=input("Enter new Phone Number: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Phone_number = '"+e2+"' where Phone_number = '"+phone+"'" )
                        print("Phone number updated")
                        mydb.commit()
                    if v1=='c':
                        e3=input("Enter new group: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set group_name = '"+e3+"' where Phone_number = '"+phone+"'" )
                        print("Group updated")
                        mydb.commit()
                    if v1=='d':
                        e4=input("Enter new address: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Address = '"+e4+"' where Phone_number = '"+phone+"'")
                        print("Address updated")
                        mydb.commit()
                    if v1=='e':
                        e5=input("Enter new city: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set City = '"+e5+"' where Phone_number = '"+phone+"'" )
                        print("City updated")
                        mydb.commit() 
                    if v1=='f':
                        e6=input("Enter new Email: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Email = '"+e6+"' where Phone_number = '"+phone+"'" )
                        print("Email updated")
                        mydb.commit()
                        print()
            elif i=='3':
                grp=input("Enter name of group whose contact would you like to see:")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("select*from contact where group_name = '"+grp+"'")
                k=mycursor.fetchall()
                for K in k:
                    print(K)
                mydb.commit()
                print()
            elif i=='4':
                cit=input("search contact by city, Enter name of city :")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("select*from contact where City = '"+cit+"'")
                h=mycursor.fetchall()
                for H in h:
                    print(H)
                mydb.commit()
                print()
                var=input("Do you want to update this contact? Y/N")
                if var=='Y':
                    print("To update Name enter: a")
                    print("To update Phone number enter: b")
                    print("To update Group enter: c")
                    print("To update Address enter: d")
                    print("To update City enter: e")
                    print("To update Email enter: f")
                    v1=input("What do you want to update?")
                    if v1=='a':
                        e1=input("Enter new name: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Name = '"+e1+"' where City = '"+cit+"'"  )
                        print("Name updated")
                        mydb.commit()
                    if v1=='b':
                        e2=input("Enter new Phone Number: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Phone_number = '"+e2+"' where City = '"+cit+"'"  )
                        print("Phone number updated")
                        mydb.commit()
                    if v1=='c':
                        e3=input("Enter new group: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set group_name = '"+e3+"' where City = '"+cit+"'"  )
                        print("Group updated")
                        mydb.commit()
                    if v1=='d':
                        e4=input("Enter new address: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Address = '"+e4+"' where City = '"+cit+"'" )
                        print("Address updated")
                        mydb.commit()
                    if v1=='e':
                        e5=input("Enter new city: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set City = '"+e5+"' where City = '"+cit+"'"  )
                        print("City updated")
                        mydb.commit() 
                    if v1=='f':
                        e6=input("Enter new Email: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Email = '"+e6+"' where City = '"+cit+"'" )
                        print("Email updated")
                        mydb.commit()
                        print()

            elif i=='5':
                mail=input("Enter mail you want to search:")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("select*from contact where Email = '"+mail+"'")
                p=mycursor.fetchall()
                for P in p:
                    print(P)
                mydb.commit()
                print()
                var=input("Do you want to update this contact? Y/N")
                if var=='Y':
                    print("To update Name enter: a")
                    print("To update Phone number enter: b")
                    print("To update Group enter: c")
                    print("To update Address enter: d")
                    print("To update City enter: e")
                    print("To update Email enter: f")
                    v1=input("What do you want to update?")
                    if v1=='a':
                        e1=input("Enter new name: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Name = '"+e1+"' where Email = '"+mail+"'"  )
                        print("Name updated")
                        mydb.commit()
                    if v1=='b':
                        e2=input("Enter new Phone Number: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Phone_number = '"+e2+"' where Email = '"+mail+"'"  )
                        print("Phone number updated")
                        mydb.commit()
                    if v1=='c':
                        e3=input("Enter new group: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set group_name = '"+e3+"' where Email = '"+mail+"'"   )
                        print("Group updated")
                        mydb.commit()
                    if v1=='d':
                        e4=input("Enter new address: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Address = '"+e4+"' where Email = '"+mail+"'" )
                        print("Address updated")
                        mydb.commit()
                    if v1=='e':
                        e5=input("Enter new city: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set City = '"+e5+"' where Email = '"+mail+"'"  )
                        print("City updated")
                        mydb.commit() 
                    if v1=='f':
                        e6=input("Enter new Email: ")
                        mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                        mycursor=mydb.cursor()
                        mycursor.execute("use project")
                        print()
                        mycursor.execute("update contact set Email = '"+e6+"' where Email = '"+mail+"'" )
                        print("Email updated")
                        mydb.commit()
                        print()
        elif c==4:
            print("1:delete by name","2:delete by phone number","3:delete by group","4:delete by city","5:delete by email",sep="\n")
            F=input("delete by?")
            if F=='1':
                name1=input("Enter name of person you want contact to be deleted:")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("delete from contact where Name = '"+name1+"'")
                print("successfully deleted")
                mydb.commit()
                print()
            elif F=='2':
                phone1=input("Enter phone number to be deleted:")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("delete from contact where Phone_number = '"+phone1+"'")
                mydb.commit()
                print("successfully deleted")
                print()
            elif F=='3':
                grp1=input("Enter name of group whose contact would you like to delete:")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("delete from contact where group_name = '"+grp1+"'")
                mydb.commit()
                print("successfully deleted")
                print()
            elif F=='4':
                cit1=input("Delete contact by city, Enter name of city :")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("delete from contact where City = '"+cit1+"'")
                mydb.commit()
                print("successfully deleted")
                print() 
            elif F=='5':
                mail1=input("Enter mail you want to search:")
                mydb=mysql.connector.connect(host="localhost",user="root",passwd="12345")
                mycursor=mydb.cursor()
                mycursor.execute("use project")
                print()
                mycursor.execute("delete from contact where Email = '"+mail1+"'")
                mydb.commit()
                print("successfully deleted")
                print()

        elif c==5:
            j=False
            break
            
            
